name: Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2.0.0
        with:
          github_user: "nadeemsangrasi"  # Your GitHub username
          svg_out: "output/github-contribution-grid-snake.svg"  # Output file name

      - name: Commit and Push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "Update contribution graph"
          add: "output/github-contribution-grid-snake.svg"
